ECommerceShop/ECommerceShop/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ECommerceShop.Data;
using ECommerceShop.Models;
using Microsoft.AspNetCore.Identity;
using ECommerceShop.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace ECommerceShop.Controllers
{
    [Authorize]
    public class BooksController : Controller
    {
        private readonly ApplicationDbContext _context;
        public readonly UserManager<IdentityUser> _userManager;
       
        public BooksController(ApplicationDbContext context, UserManager<IdentityUser> _userManager)
        {
            _context = context;
            this._userManager = _userManager;
        }

        // GET: Products
        public async Task<IActionResult> Index(string book)
        {
            if (!String.IsNullOrEmpty(book))
            {
                return View( _context.Books.Where(p => p.Title.Contains(book) || p.Genre.Contains(book)).ToList());
            }
            else
            {
                return View( _context.Books.ToList());
            }

        }

        public async Task<IActionResult> Search(String book)
        {
           
            if (!String.IsNullOrEmpty(book))
            {
                return View(await _context.Books.Where(p => p.Title.Contains(book) || p.Genre.Contains(book)).ToListAsync());
            }
            else
            {
                return View(_context.Books.Include(p => p.Author).Include(p => p.Genre));
            }

        }

        public async Task<IActionResult> SeeMyProducts()
        {
            List<ProductQuantityViewModel> myProducts = new List<ProductQuantityViewModel>();
            var userId = _userManager.GetUserId(HttpContext.User);
            var user = await _userManager.FindByIdAsync(userId) as MyUser;
            var userProducts = _context.UserProducts.Where(up => up.UserId.Equals(userId)).ToList();
            foreach(var userProduct in userProducts)
            {
                foreach(var product in await _context.Books.ToListAsync())
                {
                    if(product.BookId == userProduct.BookId)
                    {
                        ProductQuantityViewModel modelProduct = new ProductQuantityViewModel();
                        modelProduct.Name = product.Title;
                        modelProduct.Price = product.Price;
                        modelProduct.Id = product.BookId;
                        modelProduct.Quantity = userProduct.Quantity;
                        myProducts.Add(modelProduct);
                    }
                }
            }
            return View(myProducts);
        }


        public async Task<IActionResult> AddProductToShoppingCart(decimal Price, int Id)
        {
            UserProduct userProduct = new UserProduct();
            var userId = _userManager.GetUserId(HttpContext.User);
            var user = await _userManager.FindByIdAsync(userId) as MyUser;
            user.NoOfItems++;
            user.TotalPrice += Price;
            var theUserProduct = await _context.UserProducts
                .FirstOrDefaultAsync(up => up.BookId == Id && up.UserId.Equals(userId));
            if (theUserProduct != null)
            {
                theUserProduct.Quantity++;
            }
            else
            {
                userProduct.UserId = userId;
                userProduct.BookId = Id;
                userProduct.Quantity = 1;
                _context.UserProducts.Add(userProduct);
            }
            await _context.SaveChangesAsync();

            List<ProductQuantityViewModel> myProducts = new List<ProductQuantityViewModel>();
            var userProducts = _context.UserProducts.Where(up => up.UserId.Equals(userId)).ToList();
            foreach (var userProduct1 in userProducts)
            {
                foreach (var product in await _context.Books.ToListAsync())
                {
                    if (product.BookId == userProduct1.BookId)
                    {
                        ProductQuantityViewModel modelProduct = new ProductQuantityViewModel();
                        modelProduct.Name = product.Title;
                        modelProduct.Price = product.Price;
                        modelProduct.Id = product.BookId;
                        modelProduct.Quantity = userProduct1.Quantity;
                        myProducts.Add(modelProduct);
                    }
                }
            }
            return RedirectToAction("SeeMyProducts", myProducts);
        }

        public async Task<IActionResult> RemoveProductFromShoppingCart(decimal Price, int Id)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            var user = await _userManager.FindByIdAsync(userId) as MyUser;
            user.NoOfItems--;
            user.TotalPrice -= Price;
            var theUserProduct = await _context.UserProducts
                .FirstOrDefaultAsync(up => up.BookId == Id && up.UserId.Equals(userId));
            if (theUserProduct != null)
            {
                if(theUserProduct.Quantity == 1)
                {
                    _context.UserProducts.Remove(theUserProduct);
                }
                else { 

                   theUserProduct.Quantity--;
                }
            }
            await _context.SaveChangesAsync();
            List<ProductQuantityViewModel> myProducts = new List<ProductQuantityViewModel>();
            var userProducts = _context.UserProducts.Where(up => up.UserId.Equals(userId)).ToList();
            foreach (var userProduct in userProducts)
            {
                foreach (var product in await _context.Books.ToListAsync())
                {
                    if (product.BookId == userProduct.BookId)
                    {
                        ProductQuantityViewModel modelProduct = new ProductQuantityViewModel();
                        modelProduct.Name = product.Title;
                        modelProduct.Price = product.Price;
                        modelProduct.Id = product.BookId;
                        modelProduct.Quantity = userProduct.Quantity;
                        myProducts.Add(modelProduct);
                    }
                }
            }

            return RedirectToAction("SeeMyProducts", myProducts);
        }


        public async Task<IActionResult> RemoveProduct(decimal Price, int Id)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            var user = await _userManager.FindByIdAsync(userId) as MyUser;
            var product1 = await _context.Books.FirstOrDefaultAsync(p => p.BookId == Id);
            var userProduct1 = await _context.UserProducts.FirstOrDefaultAsync(up => up.BookId == Id && up.UserId.Equals(userId));
            user.NoOfItems -= userProduct1.Quantity;
            user.TotalPrice -= userProduct1.Quantity * product1.Price;
            var theUserProduct = await _context.UserProducts
                .FirstOrDefaultAsync(up => up.BookId == Id && up.UserId.Equals(userId));
            if (theUserProduct != null)
            {
                _context.UserProducts.Remove(theUserProduct);
            }
           
            await _context.SaveChangesAsync();
            List<ProductQuantityViewModel> myProducts = new List<ProductQuantityViewModel>();
            var userProducts = _context.UserProducts.Where(up => up.UserId.Equals(userId)).ToList();
            foreach (var userProduct in userProducts)
            {
                foreach (var product in await _context.Books.ToListAsync())
                {
                    if (product.BookId == userProduct.BookId)
                    {
                        ProductQuantityViewModel modelProduct = new ProductQuantityViewModel();
                        modelProduct.Name = product.Title;
                        modelProduct.Price = product.Price;
                        modelProduct.Id = product.BookId;
                        modelProduct.Quantity = userProduct.Quantity;
                        myProducts.Add(modelProduct);
                    }
                }
            }

            return RedirectToAction("SeeMyProducts", myProducts);
        }







        public async Task<IActionResult> AddProduct(decimal Price, int Id)
        {
            UserProduct userProduct = new UserProduct();
            var userId = _userManager.GetUserId(HttpContext.User);
            var user = await _userManager.FindByIdAsync(userId) as MyUser;
            user.NoOfItems++;
            user.TotalPrice += Price;
            var theUserProduct = await _context.UserProducts
                .FirstOrDefaultAsync(up => up.BookId == Id && up.UserId.Equals(userId));
            if(theUserProduct != null)
            {
                theUserProduct.Quantity++;
            }
            else
            {
                userProduct.UserId = userId;
                userProduct.BookId = Id;
                userProduct.Quantity = 1;
                _context.UserProducts.Add(userProduct);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Books
                .FirstOrDefaultAsync(m => m.BookId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }


        public IActionResult ApplyDiscount()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> ApplyDiscount([Bind("Id")] Book product)
        {
            return View(product);

ECommerceShop/ECommerceShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <title>@ViewData["Title"] - BookZone</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookZone</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href ="~/location.html">Location</a>
                           
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ECommerceShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @** <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>*@
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>